// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ZqOCrCaP1D5XooAYtL_Moorvy0Fn2Ng',
    appId: '1:1018649504290:web:8c46a45ce88437b61f387b',
    messagingSenderId: '1018649504290',
    projectId: 'franchise-management-ea496',
    authDomain: 'franchise-management-ea496.firebaseapp.com',
    storageBucket: 'franchise-management-ea496.appspot.com',
    measurementId: 'G-S3ZLERDHW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATpaWh4e4W_wyROUglwtfUFspxmaZJM0k',
    appId: '1:1018649504290:android:0043f6f52822d04e1f387b',
    messagingSenderId: '1018649504290',
    projectId: 'franchise-management-ea496',
    storageBucket: 'franchise-management-ea496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvmMTSPvrFcbf2DrirSX8hRiBJY_kTusk',
    appId: '1:1018649504290:ios:2fd6fb970c47873c1f387b',
    messagingSenderId: '1018649504290',
    projectId: 'franchise-management-ea496',
    storageBucket: 'franchise-management-ea496.appspot.com',
    iosClientId: '1018649504290-eiciltjucgrije81dsbj5tpa39bf4qqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.franchiseManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvmMTSPvrFcbf2DrirSX8hRiBJY_kTusk',
    appId: '1:1018649504290:ios:2fd6fb970c47873c1f387b',
    messagingSenderId: '1018649504290',
    projectId: 'franchise-management-ea496',
    storageBucket: 'franchise-management-ea496.appspot.com',
    iosClientId: '1018649504290-eiciltjucgrije81dsbj5tpa39bf4qqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.franchiseManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ZqOCrCaP1D5XooAYtL_Moorvy0Fn2Ng',
    appId: '1:1018649504290:web:9e888843721ed9af1f387b',
    messagingSenderId: '1018649504290',
    projectId: 'franchise-management-ea496',
    authDomain: 'franchise-management-ea496.firebaseapp.com',
    storageBucket: 'franchise-management-ea496.appspot.com',
    measurementId: 'G-CK13QL3K46',
  );

}